#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Feb 13, 2020 02:34:54 PM PST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #000000
set vTcl(actual_gui_menu_analog) #e0e0e0
set vTcl(actual_gui_menu_bg) #e1e1e1
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #e0e0e0
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #000000 
    wm focusmodel $top passive
    wm geometry $top 600x486+1100+124
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Serration Magic"
    vTcl:DefineAlias "$top" "app_window" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab44 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -justify left -text {Output Directory} 
    vTcl:DefineAlias "$top.lab44" "Label_directory" vTcl:WidgetProc "app_window" 1
    label $top.lab45 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) 
    vTcl:DefineAlias "$top.lab45" "s_logo" vTcl:WidgetProc "app_window" 1
    label $top.lab47 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -text Label 
    vTcl:DefineAlias "$top.lab47" "logo" vTcl:WidgetProc "app_window" 1
    entry $top.ent48 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -insertbackground #c0c0c0 -textvariable post_directory 
    vTcl:DefineAlias "$top.ent48" "Entry_directory" vTcl:WidgetProc "app_window" 1
    button $top.but49 \
        -background #000000 -command get_dir -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Select 
    vTcl:DefineAlias "$top.but49" "choose_button" vTcl:WidgetProc "app_window" 1
    label $top.lab50 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Part Number} 
    vTcl:DefineAlias "$top.lab50" "Label_part_number" vTcl:WidgetProc "app_window" 1
    entry $top.ent51 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable part_number 
    vTcl:DefineAlias "$top.ent51" "Entry_part_no" vTcl:WidgetProc "app_window" 1
    label $top.lab52 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Program Number} 
    vTcl:DefineAlias "$top.lab52" "Label_program_number" vTcl:WidgetProc "app_window" 1
    entry $top.ent53 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable program_number 
    vTcl:DefineAlias "$top.ent53" "Entry_program_number" vTcl:WidgetProc "app_window" 1
    label $top.lab54 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Work Offset} 
    vTcl:DefineAlias "$top.lab54" "Label_work_offset" vTcl:WidgetProc "app_window" 1
    entry $top.ent55 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable work_offset 
    vTcl:DefineAlias "$top.ent55" "Entry_work_offset" vTcl:WidgetProc "app_window" 1
    label $top.lab56 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Tool Number} 
    vTcl:DefineAlias "$top.lab56" "Label_tool_number" vTcl:WidgetProc "app_window" 1
    entry $top.ent57 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable tool_number 
    vTcl:DefineAlias "$top.ent57" "Entry_tool_number" vTcl:WidgetProc "app_window" 1
    label $top.lab58 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Location of Serration:} 
    vTcl:DefineAlias "$top.lab58" "Label_location" vTcl:WidgetProc "app_window" 1
    label $top.lab59 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {X - Center} 
    vTcl:DefineAlias "$top.lab59" "Label_x_center" vTcl:WidgetProc "app_window" 1
    entry $top.ent60 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable x_center 
    vTcl:DefineAlias "$top.ent60" "Entry_x_center" vTcl:WidgetProc "app_window" 1
    label $top.lab61 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Y - Center} 
    vTcl:DefineAlias "$top.lab61" "Label_y_center" vTcl:WidgetProc "app_window" 1
    label $top.lab62 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {B - Angle} 
    vTcl:DefineAlias "$top.lab62" "Label_b" vTcl:WidgetProc "app_window" 1
    entry $top.ent63 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable y_center 
    vTcl:DefineAlias "$top.ent63" "Entry_y_center" vTcl:WidgetProc "app_window" 1
    entry $top.ent64 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable z_top 
    vTcl:DefineAlias "$top.ent64" "Entry_z" vTcl:WidgetProc "app_window" 1
    label $top.lab65 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Z - Top} 
    vTcl:DefineAlias "$top.lab65" "Label_Z_top" vTcl:WidgetProc "app_window" 1
    entry $top.ent66 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable b_angle 
    vTcl:DefineAlias "$top.ent66" "Entry_b" vTcl:WidgetProc "app_window" 1
    label $top.lab67 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Size of Serration:} 
    vTcl:DefineAlias "$top.lab67" "Labeltoolnumber_9" vTcl:WidgetProc "app_window" 1
    label $top.lab68 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text OD 
    vTcl:DefineAlias "$top.lab68" "Label_od" vTcl:WidgetProc "app_window" 1
    label $top.lab69 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text ID 
    vTcl:DefineAlias "$top.lab69" "Label_id" vTcl:WidgetProc "app_window" 1
    entry $top.ent70 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable od 
    vTcl:DefineAlias "$top.ent70" "Entry_od" vTcl:WidgetProc "app_window" 1
    entry $top.ent71 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable id 
    vTcl:DefineAlias "$top.ent71" "Entry_id" vTcl:WidgetProc "app_window" 1
    entry $top.ent72 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable pitch 
    vTcl:DefineAlias "$top.ent72" "Entry_pitch" vTcl:WidgetProc "app_window" 1
    label $top.lab73 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Pitch 
    vTcl:DefineAlias "$top.lab73" "Label_pitch" vTcl:WidgetProc "app_window" 1
    label $top.lab74 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Cut Depth} 
    vTcl:DefineAlias "$top.lab74" "Label_depth" vTcl:WidgetProc "app_window" 1
    entry $top.ent75 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable depth 
    vTcl:DefineAlias "$top.ent75" "Entry_depth" vTcl:WidgetProc "app_window" 1
    button $top.but77 \
        -activebackground #f9f9f9 -activeforeground black -background #000000 \
        -command magic -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Magic 
    vTcl:DefineAlias "$top.but77" "do_it_button" vTcl:WidgetProc "app_window" 1
    label $top.lab78 \
        -activebackground #000000 -activeforeground #c0c0c0 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Feed Rate} 
    vTcl:DefineAlias "$top.lab78" "Label_feed" vTcl:WidgetProc "app_window" 1
    entry $top.ent79 \
        -background #000000 -disabledforeground #a3a3a3 \
        -font {-family {Consolas} -size 10} -foreground #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground #c0c0c0 -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable feed_rate 
    vTcl:DefineAlias "$top.ent79" "Entry_feed_rate" vTcl:WidgetProc "app_window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -y 140 -width 121 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 480 -y 10 -width 114 -relwidth 0 -height 111 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 10 -y 10 -width 454 -relwidth 0 -height 111 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 10 -y 170 -width 494 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 520 -y 170 -width 61 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 10 -y 210 -width 81 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 10 -y 240 -width 214 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 240 -y 210 -width 131 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 260 -y 240 -width 85 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 380 -y 210 -width 91 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 390 -y 240 -width 85 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 490 -y 210 -width 91 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 500 -y 240 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -y 280 -width 141 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -y 310 -width 81 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 10 -y 340 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab61 \
        -in $top -x 130 -y 310 -width 71 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 380 -y 310 -width 71 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 140 -y 340 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent64 \
        -in $top -x 260 -y 340 -width 85 -relwidth 0 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab65 \
        -in $top -x 250 -y 310 -width 61 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent66 \
        -in $top -x 390 -y 340 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab67 \
        -in $top -x -10 -y 380 -width 131 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 10 -y 410 -width 31 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 140 -y 410 -width 21 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent70 \
        -in $top -x 10 -y 440 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent71 \
        -in $top -x 140 -y 440 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent72 \
        -in $top -x 260 -y 440 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab73 \
        -in $top -x 250 -y 410 -width 51 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab74 \
        -in $top -x 380 -y 410 -width 81 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent75 \
        -in $top -x 390 -y 440 -width 85 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.but77 \
        -in $top -x 500 -y 390 -width 81 -relwidth 0 -height 80 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab78 \
        -in $top -x 490 -y 310 -width 81 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent79 \
        -in $top -x 500 -y 340 -width 85 -height 20 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

